name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.meta.outputs.tag }}

    steps:
    - uses: actions/checkout@v4

    - name: Set image tag
      id: meta
      run: echo "tag=$(date +%s)" >> "$GITHUB_OUTPUT"

    - name: Docker Login
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u prateeklohani --password-stdin

    - name: Build Docker Image
      run: docker build . --no-cache --file Dockerfile --tag prateeklohani/geteasy-app:${{ steps.meta.outputs.tag }} --tag prateeklohani/geteasy-app:latest

    - name: Push Docker Image
      run: |
        docker push prateeklohani/geteasy-app:${{ steps.meta.outputs.tag }}
        docker push prateeklohani/geteasy-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Trigger Render Deploy
      run: |
        curl -X POST https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys \
        -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
        -H "Content-Type: application/json"

