name: Mirror to GitLab
on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          git remote add gitlab https://lohaniprateek:${{ secrets.GITLAB_TOKEN }}@gitlab.com/lohaniprateek/portfolio.git
          git push gitlab --prune +refs/heads/*:refs/heads/*
